[alias]
br = 'build --release'
rr = 'run --release'
f = 'fmt'

# Set the settings for build scripts and proc-macros.
[profile.release.build-override]
opt-level = 0
[profile.bench.build-override]
opt-level = 0

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "target-cpu=sandybridge",
]
linker = "clang"
